---
title: "mixed-effect-models"
author: "Brendi Ang"
date: "15/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
```

```{r, include=FALSE}
# ----- Read-in data

# --- Enrolments for all subjects from 1992 to 2019
subj_old <- read_csv(here::here("data/qcaa_stats_subj_part_1992-2019.csv")) %>% 
  # Remove problematic entries
  filter(is.na(X13)) %>% 
  select(-c(X13, X14))

# --- Enrolments for all subjects from 2020 to 2021 (Sep)

# Concatenate file names
filenames <- paste0("data/","qcaa_stats_subj_part_", c("2020", "2021", "2022"), ".xlsx")

# Read-in data
subj_2020 <- readxl::read_xlsx(here::here(filenames[1]), sheet = 1, col_types = "text")
subj_2021 <- readxl::read_xlsx(here::here(filenames[2]), sheet = 1, col_types = "text")
subj_2022 <- readxl::read_xlsx(here::here(filenames[3]), sheet = 1, col_types = "text")
```

```{r}
# ----- Clean variable names

# --- Enrolments based on old QCE system

subj_old <- subj_old %>% 
  janitor::clean_names() %>% 
  rename(doe_centre_code = do_e_centre_code,
         # Consistent with new qce dataset
         completion_year = cohort_year) 

# --- Enrolments based on new QCE system

subj_new <- rbind(subj_2020, subj_2021, subj_2022) %>% 
  # Remove spaces & upper-case letters in variable names
  janitor::clean_names() %>% 
  rename(doe_centre_code = do_e_centre_code)
```

```{r}
# ----- Change data types

subj_old <- subj_old %>% 
  mutate(
    completion_year = as.numeric(completion_year),
    qcaa_subject_id = as.factor(qcaa_subject_id),
    subject_type = as.factor(subject_type),
    doe_centre_code = as.factor(doe_centre_code),
    qcaa_school_id = as.factor(qcaa_school_id),
    sector = as.factor(sector),
    school_postcode = as.factor(school_postcode),
    qcaa_district = as.factor(qcaa_district)
  ) 

subj_new <- subj_new %>% 
  mutate(
    completion_year = as.numeric(completion_year),
    qcaa_subject_id = as.factor(qcaa_subject_id),
    subject_type = as.factor(subject_type),
    qcaa_school_id = as.factor(qcaa_school_id),
    sector = as.factor(sector),
    school_postcode = as.factor(school_postcode),
    qcaa_district = as.factor(qcaa_district)
  ) %>% 
  # Remove Nauru Secondary school
  filter(!is.na(qcaa_district))
```

```{r}
# ----- Impute missing values in enrolment numbers with 0

subj_old <- subj_old %>% 
  # Replace missing values in enrolment with 0
  mutate(across(.cols = year_11_enrolments:year_12_enrolments, ~ replace_na(.x, 0))) %>% 
  mutate(across(.cols = year_11_enrolments:year_12_enrolments, ~ as.numeric(.x)))

subj_new <- subj_new %>% 
  # Replace missing values in enrolment with 0
  mutate(across(.cols = unit_1_enrolments:short_course_enrolments, ~ replace_na(.x, 0))) %>% 
  mutate(across(.cols = unit_1_enrolments:short_course_enrolments, ~ as.numeric(.x)))
```

```{r}
# ----- Enrolment for mathematics and science subjects 

# --- Old QCE system

math_old <- subj_old %>% 
  filter(subject_name %in% c("Mathematics A", "Mathematics B", "Mathematics C")) %>% 
  # Consistent with names of new QCE system
  mutate(subject_name = case_when(
    subject_name == "Mathematics A" ~ "General Mathematics",
    subject_name == "Mathematics B" ~ "Mathematical Methods",
    subject_name == "Mathematics C" ~ "Specialist Mathematics",
  )) %>% 
  # Create new variable to distinguish maths and science
  mutate(subject = "Mathematics")

# Enrolment for Sciences
sci_old <- subj_old %>% 
  filter(subject_name %in% c("Agricultural Science",
                             "Biology",
                             "Chemistry",
                             "Earth Science",
                             "Marine Science",
                             "Physics",
                             "Agricultural Practices",
                             "Aquatic Practices",
                             "Science in Practice"
                             )) %>% 
  # Create new variable to distinguish maths and science
  mutate(subject = "Sciences") %>% 
  mutate(subject_name = if_else(subject_name == "Earth Science",
                                true = "Earth & Environmental Science",
                                false = subject_name))

# Combine Maths and Science subjects for the old QCE system
mathsci_old <- rbind(math_old, sci_old)


# --- New QCE system

# Enrolment for Mathematics
math_new <- subj_new %>% 
  filter(subject_name %in% c("General Mathematics",
                             "Mathematical Methods",
                             "Specialist Mathematics",
                             # Applied
                             "Essential Mathematics", 
                             # Short Courses
                             "Numeracy")) %>% 
  # Create new variable to distinguish maths and science
  mutate(subject = "Mathematics")

# Enrolment for Sciences
sci_new <- subj_new %>% 
  filter(subject_name %in% c(# General
                             "Agricultural Science",
                             "Biology",
                             "Chemistry", 
                             "Earth & Environmental Science", # new
                             "Marine Science",
                             "Physics",
                             "Psychology", # New
                             # Applied
                             "Agricultural Practices",
                             "Aquatic Practices",
                             "Science in Practice"
                             )) %>% 
  # Create new variable to distinguish maths and science
  mutate(subject = "Sciences")

# Combine maths and sciences enrolments
mathsci_new <- rbind(math_new, sci_new) %>% 
  # Remove short courses
  filter(subject_name != "Numeracy")
```

```{r}
# Group unit 1 & 2, 3 & 4 enrolments into year 11 and year 12 enrolments respectively
## Required as old system splits enrolments into two groups (year 11 and year 12 enrolments)

mathsci_new <- mathsci_new %>% 
  rowwise() %>% 
  mutate(year_11_enrolments = sum(unit_1_enrolments, unit_2_enrolments),
         year_12_enrolments = sum(unit_3_enrolments, unit_4_enrolments)) %>% 
  # Remove short course enrolments
  select(-c(unit_1_enrolments:short_course_enrolments)) %>% 
  ungroup()

# Bind enrolment data for new and old QCE system
mathsci_all <- rbind(mathsci_old, mathsci_new)
```

```{r}
# --- Clean district names

# Remove 'District' in `qcaa_district` as there are repeated districts
mathsci_all <- mathsci_all %>% 
  mutate(qcaa_district = str_to_title(qcaa_district)) %>% 
  # Remove words that has a space (\s), followed by the word "District"
  mutate(qcaa_district = str_remove_all(qcaa_district, "\\sDistrict")) %>% 
  # Remove "-" in Brisbane Ipswich district
  mutate(qcaa_district = if_else(qcaa_district == "Brisbane - Ipswich",
                                  true = "Brisbane Ipswich",
                                  false = qcaa_district))

# --- Clean sector names

mathsci_all <- mathsci_all %>% 
  # Convert to character for string manipulation
  mutate(sector = as.character(sector)) %>% 
  mutate(sector = case_when(
    sector == "SCAT" ~ "Catholic",
    sector == "SIND" ~ "Independent",
    sector == "SGOV" ~ "Government",
    TRUE ~ sector
  )) %>% 
  mutate(sector = as.factor(sector)) %>% 
  # Remove overseas sector (SOVS), and sectors with only 1 entry (JIND, SPEC) and SCOL
  filter(sector %in% c("Catholic", "Independent", "Government"))
```

```{r}
# Fix schools (`qcaa_school_id`) with two postcodes
mathsci_all <- mathsci_all %>% 
  # Change data type to facilitate change in incorrect school postcodes
  mutate(school_postcode = as.character(school_postcode)) %>% 
  # Fix incorrect postcodes
  mutate(school_postcode = case_when(
    school_postcode == "4170" ~ "4171",
    school_postcode == "4178" ~ "4179",
    school_postcode == "4214" ~ "4215",
    school_postcode == "4031" ~ "4030",
    school_postcode == "4573" ~ "4561",
    school_postcode == "4064" ~ "4000",
    school_postcode == "4208" ~ "4209",
    TRUE ~ school_postcode
  ))

# --- Change data types
mathsci_all <- mathsci_all %>% 
  mutate(across(.cols = c(subject_name,
                          subject_type,
                          qcaa_school_id,
                          school_postcode,
                          qcaa_district,
                          sector),
                ~ as.factor(.x)))

# Reformat subject id for science in practice so they're consistent
mathsci_all <- mathsci_all %>%  
  mutate(qcaa_subject_id = as.character(qcaa_subject_id)) %>% 
  mutate(qcaa_subject_id = as.factor(if_else(qcaa_subject_id == "6248", 
                                   true = "6421",
                                   false = qcaa_subject_id)))
```

```{r}
# --- Clean school names

mathsci_all <- mathsci_all %>% 
  # Remove parentheses relating to suburb
  mutate(school_name = str_remove(school_name, " \\(.*\\)")) %>% 
  # Remove suburb by extracting all text before the last "-"
  mutate(school_name = str_replace(school_name, pattern = '(.*)\\s+\\-.*', '\\1'))

mathsci_all <- mathsci_all %>% 
  mutate(school_name = case_when(
    # Capital K in MacKillop
    school_name == "Clairvaux Mackillop College" ~ "Clairvaux MacKillop College",
    # Extra " ' " in Girls
    school_name == "St Aidan's Anglican Girls' School" ~ "St Aidan's Anglican Girls School",
    # Missing "School"
    school_name == "Aviation High" ~ "Aviation High School",
    # "&" to "and"
    school_name == "Aboriginal & Islander Independent Community School" ~ "Aboriginal and Islander Independent Community School",
    # Extra "The"
    school_name == "The SCOTS PGC College" ~ "Scots PGC College",
    school_name == "Kingston Centre for Continuing Secondary Education" ~ "Kingston Learning College",
    # Exclude suburb
    school_name == "Marist College Emerald" ~ "Marist College",
    # Change to official school name
    school_name == "The Cathedral School" ~ "The Cathedral School of St Anne and St James",
    # Exclude suburb
    school_name == "St Andrew's Catholic College Redlynch Valley" ~ "St Andrew's Catholic College",
    # Exclude suburb
    school_name == "Spinifex State College Mount Isa" ~ "Spinifex State College",
    # Error in school name
    school_name == "Cloncurry State School P-12" ~ "Cloncurry State School",
    # Error in school name
    school_name == "Cloncurry State School P" ~ "Cloncurry State School",
    TRUE ~ school_name
  ))
``` 

```{r}
# --- Change subject type based on the new QCE system (General or applied)
mathsci_all <- mathsci_all %>% 
  mutate(subject_type = case_when(
    # General mathematics
    subject_name == "General Mathematics" ~  "General",
    subject_name == "Mathematical Methods" ~ "General",
    subject_name == "Specialist Mathematics" ~ "General",
    # Applied mathematics
    subject_name == "Essential Mathematics" ~ "Applied",
    # General sciences
    subject_name == "Agricultural Science" ~  "General",
    subject_name == "Biology" ~  "General",
    subject_name == "Chemistry" ~ "General",
    subject_name == "Earth & Environmental Science" ~ "General",
    subject_name == "Marine Science" ~ "General",
    subject_name == "Physics" ~ "General",
    subject_name == "Psychology" ~ "General",
    # Applied sciences
    subject_name == "Agricultural Practices" ~ "Applied",
    subject_name == "Aquatic Practices" ~ "Applied",
    subject_name == "Science in Practice" ~ "Applied"
  ))
```



```{r, eval=FALSE}
# ----- Write data
write_csv(mathsci_all, here::here("data/mathsci_all.csv"))
```



